lint.select=["E", "F", "I", "W", "N", "UP", "ANN"]
lint.ignore=["ANN001", "ANN002", "ANN003", "ANN201", "N801", "N802", "N803", "N806", "N815", "N999", "F403", "F405", "E501", "E731", "UP035", "UP006", "UP007", "UP045"]
